# Offline Meeting Records configuration
# 所有路径均为相对项目根目录的路径
recording:
  sample_rate: 16000        # 录音采样率 (Hz)
  channels: 1               # 单声道录音
  chunk_seconds: 600        # 每个音频切片时长 (秒)
  device: null              # 指定录音设备索引，null 表示使用默认设备

storage:
  retain_audio_days: 0      # 音频保留天数 (0 表示生成纪要后立即删除)
  retain_transcript_days: 7 # 转写文本默认保留天数

paths:
  audio_dir: audio_in
  markers_dir: markers
  transcript_dir: transcripts
  summary_dir: summaries
  minutes_dir: minutes
  policy_source_dir: policy_source
  policy_db_dir: policy_db
  models_dir: models

asr:
  engine: vosk                      # 识别引擎，默认使用 Vosk
  sdelete_path: bin/sdelete64.exe

asr:
  model_path: models/vosk-model-cn  # 请自行下载 Vosk 中文模型并解压到该目录
  max_alternatives: 0
  words: true

summary:
  quick_filename: quick.md
  proofreading_prefix: sum_
  diff_prefix: diff_
  action_items_filename: actions.json
  contact_csv: contacts/contacts.csv   # 科室通讯录（CSV），列名含 name 或第一列为姓名
  default_template: 通用              # 导出纪要默认模板：通用/党委会/项目会/招采会

policy:
  database_name: policy.db
  snippet_length: 200
  top_k: 5

secure_delete:
  mode: sdelete              # 可选：sdelete / standard
  sdelete_path: bin/sdelete64.exe
  overwrite_passes: 1        # SDelete 覆盖次数
  fallback_message: "未检测到 SDelete，已使用普通删除。建议启用 BitLocker/全盘加密。"

logging:
  log_file: null             # 若需记录操作日志，请填写路径；默认为空表示不记录
security:
  overwrite_passes: 1      # SDelete 覆盖次数
  log_file: null           # 若需记录操作日志，请填写路径；默认为空表示不记录
