name: Windows Build

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build executable
        run: |
          pyinstaller --noconfirm --clean --name OfflineMeetingRecords \
            --add-data "config.yaml;." \
            --add-data "policy_source;policy_source" \
            --add-data "models;models" \
            app.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OfflineMeetingRecords
          path: dist/OfflineMeetingRecords/
