name: Windows Build

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Prepare data directories
        run: |
          New-Item -ItemType Directory -Force -Path models | Out-Null
          New-Item -ItemType Directory -Force -Path policy_db | Out-Null
          New-Item -ItemType Directory -Force -Path bin | Out-Null
      - name: Build executable
        shell: pwsh
        run: |
          pyinstaller --noconfirm --clean --name LocalMeetingBot `
            --noconsole `
            --add-data "config.yaml;." `
            --add-data "models;models" `
            --add-data "policy_db;policy_db" `
            --add-data "bin;bin" `
            app.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LocalMeetingBot_win
          path: dist/LocalMeetingBot/
